version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null

  - name: dim_products
    columns:
      - name: product_key
        tests:
          - unique
          - not_null

  - name: fact_sales
    columns:
      - name: order_number
        tests:
          - not_null